Revert "arm64: Cortex-A53/ARMv8 optimizations for msm8953/sdm450"
This reverts commit 814ef25a2baed4902c2cd9c937710540f9d6fc2c.

Log:
error: unknown target CPU 'cortex-a53'

To aosp clang

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I6972633014252083ad1587c768244bae4a7f303a