Revert "wifi: ath9k: htc_hst: free skb in ath9k_htc_rx_msg() if there is no callback function"
This reverts commit 848d17b201996c54a0733960a67f96a1e7d65d17.

log:
../drivers/net/wireless/ath/ath9k/htc_hst.c:476:9: error: use of undeclared label 'invalid'
                        goto invalid;
                             ^
1 error generated.

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Ifec8dbdd361ba99b35c9c44a9a72ff221a4be5e3